const DEFAULT_PORT = 8000;

const DEFAULT_SECRET = "3rZ;w4Hy:{(2%z#xa:'x/p#.`:p@3eG)";

const DEFAULT_CORS_ORIGIN = "PROD_URL";

const COOKIE_NAME = "PROJECT_NAME";

const DEFAULT_REDIS_URL = "127.0.0.1:6379";

export {
  DEFAULT_PORT,
  DEFAULT_SECRET,
  DEFAULT_CORS_ORIGIN,
  COOKIE_NAME,
  DEFAULT_REDIS_URL,
};
